apiVersion: apps/v1
kind: Deployment
metadata:
  name: bultgang
  namespace: wolf
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bultgang
  template:
    metadata:
      labels:
        name: bultgang
    spec:
      containers:
      - name: bultgang
        image: xiaoweihong/bultgang:0.6.4
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 18082
        command: ["./bultgang"]
        args:
        - "-stderrthreshold=0"
        - "-logtostderr=true"
        - "-v=8"
        volumeMounts:
        - name: bultgang-config
          mountPath: /bultgang/config.json
          subPath: config.json
      volumes:
        - name: bultgang-config
          configMap:
            name: bultgang-config
