apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-deployment
  namespace: deepdata-warwolf
spec:
  replicas: 1
  selector:
    matchLabels:
      name: volume
  template:
    metadata:
      labels:
        name: volume 
    spec:
      containers:
      - name: seaweedfs-volume
        image: chrislusf/seaweedfs:1.44
        ports:
        - name: http
          containerPort: 9300
        - name: grpc
          containerPort: 19300
        args:
          - "volume"
          - "-mserver=master-seaweedfs-service.deepdata-warwolf.svc.cluster.local:9333"
          - "-ip=master-seaweedfs-service.deepdata-warwolf.svc.cluster.local"
          - "-port=9300"
          - "-publicUrl=192.168.2.113:30300"
          - "-port.public=8000"
          - "-dir=/data"
        volumeMounts:
        - mountPath: /data
          name: volume-data
      volumes:
      - name: volume-data
        hostPath:
          path: /data/seaweedfs/volume
