apiVersion: v1
kind: Service
metadata:
  name: odin-service
  namespace: wolf
spec:
  type: NodePort
  selector:
    name: odin
  ports:
  - name: http
    port: 1989
    targetPort: 1989
    nodePort: 30089
