apiVersion: apps/v1
kind: Deployment
metadata:
  name: croatia
  namespace: wolf
spec:
  replicas: 1
  selector:
    matchLabels:
      name: croatia
  template:
    metadata:
      labels:
        name: croatia
    spec:
      containers:
      - name: croatia
        image: xiaoweihong/croatia:0.6.4
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 18082
        command: ["./croatia"]
        args:
        - "-stderrthreshold=0"
        - "-logtostderr=true"
        - "-v=8"
        volumeMounts:
        - name: croatia-config
          mountPath: /croatia/config.json
          subPath: config.json
      volumes:
        - name: croatia-config
          configMap:
            name: croatia-config
